import SwiftUI
import shared

struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard)
    }
}

/// Hosts the KMP Compose UI in a UIKit-bridged UIViewController.
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // BeautyClientAppViewControllerKt is generated by the KMP framework.
        // It calls BeautyClientApp() from the shared module.
        return BeautyClientAppViewControllerKt.BeautyClientAppViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
