package com.andrey.beautyplanner

object CurrencyNames {

    /**
     * names["UAH"]?.get("uk") => "Українська гривня"
     */
    private val names: Map<String, Map<String, String>> = mapOf(
        "EUR" to mapOf(
            "ar" to "يورو",
            "bg" to "Евро",
            "cs" to "Euro",
            "da" to "Euro",
            "de" to "Euro",
            "el" to "Еυρώ",
            "en" to "Euro",
            "es" to "Euro",
            "et" to "Euro",
            "fi" to "Euro",
            "fr" to "Euro",
            "hi" to "यूरो",
            "hu" to "Euró",
            "id" to "Euro",
            "it" to "Euro",
            "ja" to "ユーロ",
            "ko" to "유로",
            "lt" to "Euras",
            "lv" to "Eiro",
            "nl" to "Euro",
            "no" to "Euro",
            "pl" to "Euro",
            "pt-BR" to "Euro",
            "ro" to "Euro",
            "ru" to "Евро",
            "sk" to "Euro",
            "sl" to "Evro",
            "sr" to "Евро",
            "sv" to "Euro",
            "tr" to "Euro",
            "uk" to "Євро",
            "zh" to "欧元"
        ),
        "USD" to mapOf(
            "ar" to "دولار أمريكي",
            "bg" to "Щатски долар",
            "cs" to "Americký dolar",
            "da" to "Amerikansk dollar",
            "de" to "US-Dollar",
            "el" to "Δολάριο ΗΠΑ",
            "en" to "US Dollar",
            "es" to "Dólar estadounidense",
            "et" to "USA dollar",
            "fi" to "Yhdysvaltain dollari",
            "fr" to "Dollar américain",
            "hi" to "अमेरिकी डॉलर",
            "hu" to "Amerikai dollár",
            "id" to "Dolar Amerika Serikat",
            "it" to "Dollaro statunitense",
            "ja" to "米ドル",
            "ko" to "미국 달러",
            "lt" to "JAV doleris",
            "lv" to "ASV dolārs",
            "nl" to "Amerikaanse dollar",
            "no" to "Amerikansk dollar",
            "pl" to "Dolar amerykański",
            "pt-BR" to "Dólar americano",
            "ro" to "Dollar american",
            "ru" to "Американский доллар",
            "sk" to "Americký dolár",
            "sl" to "Ameriški dolar",
            "sr" to "Амерички долар",
            "sv" to "Amerikansk dollar",
            "tr" to "ABD Doları",
            "uk" to "Долар США",
            "zh" to "美元"
        ),
        "UAH" to mapOf(
            "ar" to "هريفنا أوكرانية",
            "bg" to "Украинска гривня",
            "cs" to "Ukrajinská hřivna",
            "da" to "Ukrainsk hryvnia",
            "de" to "Ukrainische Hrywnja",
            "el" to "Χρίβνια Ουκρανίας",
            "en" to "Ukrainian Hryvnia",
            "es" to "Grivna ucraniana",
            "et" to "Ukraina grivna",
            "fi" to "Ukrainan hryvnia",
            "fr" to "Hryvnia ukrainienne",
            "hi" to "यूक्रेनी रिव्निया",
            "hu" to "Ukran hrivnya",
            "id" to "Hryvnia Ukraina",
            "it" to "Grivnia ucraina",
            "ja" to "ウクライナ・グリブナ",
            "ko" to "우크라이나 흐리브냐",
            "lt" to "Ukrainos grivina",
            "lv" to "Ukrainas grivna",
            "nl" to "Oekraïense hryvnia",
            "no" to "Ukrainsk hryvnia",
            "pl" to "Hrywna ukraińska",
            "pt-BR" to "Hryvnia ucraniana",
            "ro" to "Hryvna ucraineană",
            "ru" to "Украинская гривна",
            "sk" to "Ukrajinská hrivna",
            "sl" to "Ukrajinska grivna",
            "sr" to "Украјинска гривна",
            "sv" to "Ukrainsk hryvnia",
            "tr" to "Ukrayna Grivnası",
            "uk" to "Українська гривня",
            "zh" to "乌克兰格里夫纳"
        ),
        "RUB" to mapOf(
            "ar" to "روبل روسي",
            "bg" to "Руска рубла",
            "cs" to "Ruský rubl",
            "da" to "Russisk rubel",
            "de" to "Russischer Rubel",
            "el" to "Ρωσικό ρούβλι",
            "en" to "Russian Ruble",
            "es" to "Rublo ruso",
            "et" to "Venemaa rubla",
            "fi" to "Venäjän rupla",
            "fr" to "Rouble russe",
            "hi" to "रूसी रूबल",
            "hu" to "Orosz rubel",
            "id" to "Rubel Rusia",
            "it" to "Rublo russo",
            "ja" to "ロシア・ルーブル",
            "ko" to "러시아 루블",
            "lt" to "Rusijos rublis",
            "lv" to "Krievijas rublis",
            "nl" to "Russische roebel",
            "no" to "Russisk rubel",
            "pl" to "Rubel rosyjski",
            "pt-BR" to "Rublo russo",
            "ro" to "Rublă rusească",
            "ru" to "Российский рубль",
            "sk" to "Ruský rubeľ",
            "sl" to "Ruska rubeljska",
            "sr" to "Руска рубља",
            "sv" to "Rysk rubel",
            "tr" to "Rus Rublesi",
            "uk" to "Російський рубль",
            "zh" to "俄罗斯卢布"
        ),
        "GBP" to mapOf(
            "ar" to "جنيه إسترليني",
            "bg" to "Британска лира",
            "cs" to "Britská libra",
            "da" to "Britiskt pund",
            "de" to "Britisches Pfund",
            "el" to "Λίρα Στερλίνα",
            "en" to "British Pound",
            "es" to "Libra esterlina",
            "et" to "Suurbritannia naelsterling",
            "fi" to "Englannin punta",
            "fr" to "Livre sterling",
            "hi" to "ब्रिटिश पाउंड",
            "hu" to "Font sterling",
            "id" to "Pound Inggris",
            "it" to "Sterlina britannica",
            "ja" to "英ポンド",
            "ko" to "영국 파운드",
            "lt" to "Didžiosios Britanijos svaras",
            "lv" to "Lielbritānijas mārciņa",
            "nl" to "Brits pond",
            "no" to "Britiskt pund",
            "pl" to "Funt szterling",
            "pt-BR" to "Libra esterlina",
            "ro" to "Liră sterlină",
            "ru" to "Фунт стерлингов",
            "sk" to "Britská libra",
            "sl" to "Britanski funt",
            "sr" to "Британска фунта",
            "sv" to "Britiskt pund",
            "tr" to "İngiliz Sterlini",
            "uk" to "Фунт стерлінгів",
            "zh" to "英镑"
        ),
        "PLN" to mapOf(
            "ar" to "زلوتي بولندي",
            "bg" to "Полска злота",
            "cs" to "Polský zlotý",
            "da" to "Polsk zloty",
            "de" to "Polnischer Złoty",
            "el" to "Ζλότι Πολωνίας",
            "en" to "Polish Złoty",
            "es" to "Złoty polaco",
            "et" to "Poola zlott",
            "fi" to "Puolan zloti",
            "fr" to "Złoty polonais",
            "hi" to "पॉलिश ज़्लॉटी",
            "hu" to "Lengyel zloty",
            "id" to "Zloty Polandia",
            "it" to "Złoty polacco",
            "ja" to "ポーランド・ズウォティ",
            "ko" to "폴란드 즈워티",
            "lt" to "Lenkijos zlotas",
            "lv" to "Polijas zlots",
            "nl" to "Poolse zloty",
            "no" to "Polsk zloty",
            "pl" to "Polski złoty",
            "pt-BR" to "Zloty polonês",
            "ro" to "Zlot polonez",
            "ru" to "Польский злотый",
            "sk" to "Poľský zlotý",
            "sl" to "Poljski zlot",
            "sr" to "Пољски злот",
            "sv" to "Polsk zloty",
            "tr" to "Polonya Zlotisi",
            "uk" to "Польський злотий",
            "zh" to "波兰兹罗提"
        ),
        "TRY" to mapOf(
            "ar" to "ليرة تركية",
            "bg" to "Турска лира",
            "cs" to "Turecká lira",
            "da" to "Tyrkisk lire",
            "de" to "Türkische Lira",
            "el" to "Λίρα Τουρκίας",
            "en" to "Turkish Lira",
            "es" to "Lira turca",
            "et" to "Türgi liir",
            "fi" to "Turkin liira",
            "fr" to "Livre turque",
            "hi" to "तुर्की लीरा",
            "hu" to "Török líra",
            "id" to "Lira Turki",
            "it" to "Lira turca",
            "ja" to "トルコリラ",
            "ko" to "터키 리라",
            "lt" to "Turkijos lira",
            "lv" to "Turcijas lira",
            "nl" to "Turkse lira",
            "no" to "Tyrkisk lire",
            "pl" to "Lira turecka",
            "pt-BR" to "Lira turca",
            "ro" to "Liră turcească",
            "ru" to "Турецкая лира",
            "sk" to "Turecká líra",
            "sl" to "Turška lira",
            "sr" to "Турска лира",
            "sv" to "Turkisk lira",
            "tr" to "Türk Lirası",
            "uk" to "Турецька ліра",
            "zh" to "土耳其里拉"
        ),
        "JPY" to mapOf(
            "ar" to "ين ياباني",
            "bg" to "Японска йена",
            "cs" to "Japonský jen",
            "da" to "Japansk yen",
            "de" to "Japanischer Yen",
            "el" to "Γεν Ιαπωνίας",
            "en" to "Japanese Yen",
            "es" to "Yen japonés",
            "et" to "Jaapani jeen",
            "fi" to "Japanin jeni",
            "fr" to "Yen japonais",
            "hi" to "जापानी येन",
            "hu" to "Japán jen",
            "id" to "Yen Jepang",
            "it" to "Yen giapponese",
            "ja" to "日本円",
            "ko" to "일본 엔",
            "lt" to "Japonijos jena",
            "lv" to "Japānas jena",
            "nl" to "Japanse yen",
            "no" to "Japansk yen",
            "pl" to "Jen japoński",
            "pt-BR" to "Iene japonês",
            "ro" to "Yen japonez",
            "ru" to "Японская иена",
            "sk" to "Japonský jen",
            "sl" to "Japonski jen",
            "sr" to "Јапански јен",
            "sv" to "Japansk yen",
            "tr" to "Japon Yeni",
            "uk" to "Японська єна",
            "zh" to "日元"
        ),
        "CNY" to mapOf(
            "ar" to "يوان صيني",
            "bg" to "Китайски юан",
            "cs" to "Čínský jüan",
            "da" to "Kinesisk yuan",
            "de" to "Chinesischer Yuan",
            "el" to "Γουάν Κίνας",
            "en" to "Chinese Yuan",
            "es" to "Yuan chino",
            "et" to "Hiina jüan",
            "fi" to "Kiinan juan",
            "fr" to "Yuan chinois",
            "hi" to "चीनी युआन",
            "hu" to "Kínai jüan",
            "id" to "Yuan Tiongkok",
            "it" to "Yuan cinese",
            "ja" to "中国元",
            "ko" to "중국 위안",
            "lt" to "Kinijos juanis",
            "lv" to "Ķīnas juaņa",
            "nl" to "Chinese yuan",
            "no" to "Kinesisk yuan",
            "pl" to "Juan chiński",
            "pt-BR" to "Yuan chinês",
            "ro" to "Yuan chinezesc",
            "ru" to "Китайский юань",
            "sk" to "Čínsky jüan",
            "sl" to "Kitajski juan",
            "sr" to "Кинески јуан",
            "sv" to "Kinesisk yuan",
            "tr" to "Çin Yuanı",
            "uk" to "Китайський юань",
            "zh" to "人民币"
        ),
        "AUD" to mapOf(
            "ar" to "دولار أسترالي",
            "bg" to "Австралийски долар",
            "cs" to "Australský dolar",
            "da" to "Australsk dollar",
            "de" to "Australischer Dollar",
            "el" to "Δολάριο Αυστραλίας",
            "en" to "Australian Dollar",
            "es" to "Dólar australiano",
            "et" to "Austraalia dollar",
            "fi" to "Australian dollari",
            "fr" to "Dollar australien",
            "hi" to "ऑस्ट्रेलियाई डॉलर",
            "hu" to "Ausztrál dollár",
            "id" to "Dolar Australia",
            "it" to "Dollaro australiano",
            "ja" to "豪ドル",
            "ko" to "호주 달러",
            "lt" to "Australijos doleris",
            "lv" to "Austrālijas dolārs",
            "nl" to "Australische dollar",
            "no" to "Australsk dollar",
            "pl" to "Dolar australijski",
            "pt-BR" to "Dólar australiano",
            "ro" to "Dollar australian",
            "ru" to "Австралийский доллар",
            "sk" to "Austrálsky dolár",
            "sl" to "Avstralski dolar",
            "sr" to "Аустралијски долар",
            "sv" to "Australisk dollar",
            "tr" to "Avustralya Doları",
            "uk" to "Австралійський долар",
            "zh" to "澳元"
        ),
        "AED" to mapOf(
            "ar" to "درهم إماراتي",
            "bg" to "Дирхам на ОАЕ",
            "cs" to "Dirham SAE",
            "da" to "UAE-dirham",
            "de" to "VAE-Dirham",
            "el" to "Ντιράμ ΗΑΕ",
            "en" to "UAE Dirham",
            "es" to "Dírham de los EAU",
            "et" to "AÜE dirhem",
            "fi" to "Arabiemiirikuntien dirhami",
            "fr" to "Dirham des EAU",
            "hi" to "संयुक्त अरब अमीरात दिर्हाम",
            "hu" to "UAE-dirham",
            "id" to "Dirham UEA",
            "it" to "Dirham degli EAU",
            "ja" to "UAEディルハム",
            "ko" to "아랍에미리트 디르함",
            "lt" to "JAE dirhamas",
            "lv" to "AAE dirhams",
            "nl" to "VAE-dirham",
            "no" to "UAE dirham",
            "pl" to "Dirham ZEA",
            "pt-BR" to "Dirham dos EAU",
            "ro" to "Dirham EAU",
            "ru" to "Дирхам ОАЭ",
            "sk" to "Dirham SAE",
            "sl" to "Dirham ZAE",
            "sr" to "Дирхам ОАЕ",
            "sv" to "Förenade Arabemiratens dirham",
            "tr" to "BAE Dirhemi",
            "uk" to "Дирхам ОАЕ",
            "zh" to "阿联酋迪拉姆"
        ),
        "BRL" to mapOf(
            "ar" to "ريال برازيلي",
            "bg" to "Бразилски реал",
            "cs" to "Brazilský real",
            "da" to "Brasiliansk real",
            "de" to "Brasilianischer Real",
            "el" to "Ρεάλ Βραζιλίας",
            "en" to "Brazilian Real",
            "es" to "Real brasileño",
            "et" to "Brasiilia reaal",
            "fi" to "Brasilian real",
            "fr" to "Réal brésilien",
            "hi" to "ब्राज़ीलियाई रियाल",
            "hu" to "Brazil real",
            "id" to "Real Brasil",
            "it" to "Real brasiliano",
            "ja" to "ブラジル・レアル",
            "ko" to "브라질 헤알",
            "lt" to "Brazilijos realas",
            "lv" to "Brazīlijas reāls",
            "nl" to "Braziliaanse real",
            "no" to "Brasiliansk real",
            "pl" to "Real brazylijski",
            "pt-BR" to "Real brasileiro",
            "ro" to "Real brazilian",
            "ru" to "Бразильский реал",
            "sk" to "Brazílsky real",
            "sl" to "Brazilski real",
            "sr" to "Бразилски реал",
            "sv" to "Brasiliansk real",
            "tr" to "Brezilya Reali",
            "uk" to "Бразильський реал",
            "zh" to "巴西雷亚尔"
        ),
        "CAD" to mapOf(
            "ar" to "دولار كندي",
            "bg" to "Канадски долар",
            "cs" to "Kanadský dolar",
            "da" to "Canadisk dollar",
            "de" to "Kanadischer Dollar",
            "el" to "Δολάριο Καναδά",
            "en" to "Canadian Dollar",
            "es" to "Dólar canadiense",
            "et" to "Kanada dollar",
            "fi" to "Kanadan dollari",
            "fr" to "Dollar canadien",
            "hi" to "कनाडाई डॉलर",
            "hu" to "Kanadai dollár",
            "id" to "Dolar Kanada",
            "it" to "Dollaro canadese",
            "ja" to "カナダ・ドル",
            "ko" to "캐나다 달러",
            "lt" to "Kanados doleris",
            "lv" to "Kanādas dolārs",
            "nl" to "Canadese dollar",
            "no" to "Kanadisk dollar",
            "pl" to "Dolar kanadyjski",
            "pt-BR" to "Dólar canadense",
            "ro" to "Dollar canadian",
            "ru" to "Канадский доллар",
            "sk" to "Kanadský dolár",
            "sl" to "Kanadski dolar",
            "sr" to "Канадски долар",
            "sv" to "Kanadisk dollar",
            "tr" to "Kanada Doları",
            "uk" to "Канадський долар",
            "zh" to "加元"
        ),
        "CHF" to mapOf(
            "ar" to "فرنك سويسري",
            "bg" to "Швейцарски франк",
            "cs" to "Švýcarský frank",
            "da" to "Schweizerfranc",
            "de" to "Schweizer Franken",
            "el" to "Ελβετικό φράγκο",
            "en" to "Swiss Franc",
            "es" to "Franco suizo",
            "et" to "Šveitsi frank",
            "fi" to "Sveitsin frangi",
            "fr" to "Franc suisse",
            "hi" to "स्विस फ्रैंक",
            "hu" to "Svájci frank",
            "id" to "Franc Swiss",
            "it" to "Franco svizzero",
            "ja" to "スイス・フラン",
            "ko" to "스위스 프랑",
            "lt" to "Šveicarijos frankas",
            "lv" to "Šveices franks",
            "nl" to "Zwitserse frank",
            "no" to "Sveitserfrank",
            "pl" to "Frank szwajcarski",
            "pt-BR" to "Franco suíço",
            "ro" to "Franc elvețian",
            "ru" to "Швейцарский франк",
            "sk" to "Švajčiarsky frank",
            "sl" to "Švicarski frank",
            "sr" to "Швајцарски франак",
            "sv" to "Schweizisk franc",
            "tr" to "İsviçre Frangı",
            "uk" to "Швейцарський франк",
            "zh" to "瑞士法郎"
        ),
        "CZK" to mapOf(
            "ar" to "كرونة تشيكية",
            "bg" to "Чешка крона",
            "cs" to "Česká koruna",
            "da" to "Tjekkisk koruna",
            "de" to "Tschechische Krone",
            "el" to "Κορόνα Τσεχίας",
            "en" to "Czech Koruna",
            "es" to "Corona checa",
            "et" to "Tšehhi kroon",
            "fi" to "Tšekin koruna",
            "fr" to "Couronne tchèque",
            "hi" to "चेक कोरुना",
            "hu" to "Cseh korona",
            "id" to "Koruna Teko",
            "it" to "Corona ceca",
            "ja" to "チェコ・コルナ",
            "ko" to "체코 코루나",
            "lt" to "Čekijos krona",
            "lv" to "Čehijas krona",
            "nl" to "Tsjechische kroon",
            "no" to "Tsjekkisk koruna",
            "pl" to "Korona czeska",
            "pt-BR" to "Coroa checa",
            "ro" to "Coroană cehă",
            "ru" to "Чешская крона",
            "sk" to "Česká koruna",
            "sl" to "Češka krona",
            "sr" to "Чешка круна",
            "sv" to "Tjeckisk krona",
            "tr" to "Çek Korunası",
            "uk" to "Чеська крона",
            "zh" to "捷克克朗"
        ),
        "DKK" to mapOf(
            "ar" to "كرونة دنماركية",
            "bg" to "Датска крона",
            "cs" to "Dánská koruna",
            "da" to "Dansk krone",
            "de" to "Dänische Krone",
            "el" to "Κορόνα Δανίας",
            "en" to "Danish Krone",
            "es" to "Corona danesa",
            "et" to "Taani kroon",
            "fi" to "Tanskan kruunu",
            "fr" to "Couronne danoise",
            "hi" to "डेниш क्रोन",
            "hu" to "Dán korona",
            "id" to "Krone Denmark",
            "it" to "Corona danese",
            "ja" to "デンマーク・クローネ",
            "ko" to "덴マーク 크로네",
            "lt" to "Danijos krona",
            "lv" to "Dānijas krona",
            "nl" to "Deense kroon",
            "no" to "Dansk krone",
            "pl" to "Korona duńska",
            "pt-BR" to "Coroa dinamarquesa",
            "ro" to "Coroană daneză",
            "ru" to "Датская крона",
            "sk" to "Dánska koruna",
            "sl" to "Danska krona",
            "sr" to "Данска круна",
            "sv" to "Dansk krona",
            "tr" to "Danimarka Kronu",
            "uk" to "Данська крона",
            "zh" to "丹麦克朗"
        ),
        "HUF" to mapOf(
            "ar" to "فورنت مجري",
            "bg" to "Унгарски форинт",
            "cs" to "Maďarský forint",
            "da" to "Ungarsk forint",
            "de" to "Ungarischer Forint",
            "el" to "Φιορίνι Ουγγαρίας",
            "en" to "Hungarian Forint",
            "es" to "Forinto húngaro",
            "et" to "Ungari forint",
            "fi" to "Unkarin forintti",
            "fr" to "Forint hongrois",
            "hi" to "हंगेरियन फ़ोरिंट",
            "hu" to "Magyar forint",
            "id" to "Forint Hungaria",
            "it" to "Fiorino ungherese",
            "ja" to "ハンガリー・フォリント",
            "ko" to "헝가리 포린트",
            "lt" to "Vengrijos forintas",
            "lv" to "Ungārijas forints",
            "nl" to "Hongaarse forint",
            "no" to "Ungarsk forint",
            "pl" to "Forint węgierski",
            "pt-BR" to "Forint húngaro",
            "ro" to "Forint maghiar",
            "ru" to "Венгерский форинт",
            "sk" to "Maďarský forint",
            "sl" to "Madžarski forint",
            "sr" to "Мађарска форинта",
            "sv" to "Ungersk forint",
            "tr" to "Macar Forinti",
            "uk" to "Угорський форинт",
            "zh" to "匈牙利福林"
        ),
        "INR" to mapOf(
            "ar" to "روبية هندية",
            "bg" to "Индийска рупия",
            "cs" to "Indická rupie",
            "da" to "Indisk rupee",
            "de" to "Indische Rupie",
            "el" to "Ρουπία Инδίας",
            "en" to "Indian Rupee",
            "es" to "Rupia india",
            "et" to "India ruupia",
            "fi" to "Intian rupia",
            "fr" to "Roupie indienne",
            "hi" to "भारतीय रुपया",
            "hu" to "Indiai rúpia",
            "id" to "Rupee India",
            "it" to "Rupia indiana",
            "ja" to "インド・ルピー",
            "ko" to "인도 루피",
            "lt" to "Indijos rupija",
            "lv" to "Indijas rūpija",
            "nl" to "Indiase roepie",
            "no" to "Indisk rupee",
            "pl" to "Rupia indyjska",
            "pt-BR" to "Rupia indiana",
            "ro" to "Rupie indiană",
            "ru" to "Индийская рупия",
            "sk" to "Indická rupia",
            "sl" to "Indijska rupija",
            "sr" to "Индијска рупија",
            "sv" to "Indisk rupee",
            "tr" to "Hindistan Rupisi",
            "uk" to "Індійська рупія",
            "zh" to "印度卢比"
        ),
        "KRW" to mapOf(
            "ar" to "وون كوريا الجنوبية",
            "bg" to "Южнокорейски вон",
            "cs" to "Jihokorejský won",
            "da" to "Sydkoreansk won",
            "de" to "Südkoreanischer Won",
            "el" to "Γουόν Νότιας Κορέας",
            "en" to "South Korean Won",
            "es" to "Won surcoreano",
            "et" to "Lõuna-Korea vonn",
            "fi" to "Etelä-Korean won",
            "fr" to "Won sud-coréen",
            "hi" to "दक्षिण कोरियाई वॉन",
            "hu" to "Dél-koreai von",
            "id" to "Won Korea Selatan",
            "it" to "Won sudcoreano",
            "ja" to "韓国ウォン",
            "ko" to "대한민국 원",
            "lt" to "Pietų Korėjos vonas",
            "lv" to "Dienvidkorejas vona",
            "nl" to "Zuid-Koreaanse won",
            "no" to "Sydkoreansk won",
            "pl" to "Won południowokoreański",
            "pt-BR" to "Won sul-coreano",
            "ro" to "Won sud-coreean",
            "ru" to "Южнокорейская вона",
            "sk" to "Južnokórejský von",
            "sl" to "Južnokorejski von",
            "sr" to "Јужнокорејски вон",
            "sv" to "Sydkoreansk won",
            "tr" to "Güney Kore Wonu",
            "uk" to "Південнокорейська вона",
            "zh" to "韩元"
        ),
        "KZT" to mapOf(
            "ar" to "تينغ كازاخستاني",
            "bg" to "Казахстанско тенге",
            "cs" to "Kazachstánské tenge",
            "da" to "Kasakhisk tenge",
            "de" to "Kasachischer Tenge",
            "el" to "Τένγκε Καζακστάν",
            "en" to "Kazakhstani Tenge",
            "es" to "Tenge kazajo",
            "et" to "Kasahstani tenge",
            "fi" to "Kazakstanin tenge",
            "fr" to "Tenge kazakh",
            "hi" to "कज़ाखस्तानी टेंग",
            "hu" to "Kazahsztáni tenge",
            "id" to "Tenge Kazakstan",
            "it" to "Tenge kazako",
            "ja" to "カザフスタン・テンゲ",
            "ko" to "카자흐스탄 텐게",
            "lt" to "Kazachstano tengė",
            "lv" to "Kazahstānas tenge",
            "nl" to "Kazachstaanse tenge",
            "no" to "Kasakhisk tenge",
            "pl" to "Tenge kazachskie",
            "pt-BR" to "Tenge cazaque",
            "ro" to "Tenge kazahă",
            "ru" to "Казахстанский тенге",
            "sk" to "Kazachstanské tenge",
            "sl" to "Kazahstanski tenge",
            "sr" to "Казахстански тенге",
            "sv" to "Kazakstansk tenge",
            "tr" to "Kazakistan Tengesi",
            "uk" to "Казахстанський тенге",
            "zh" to "哈萨克斯坦坚戈"
        ),
        "MXN" to mapOf(
            "ar" to "بيسو مكسيكي",
            "bg" to "Мексиканско песо",
            "cs" to "Mexické peso",
            "da" to "Mexicansk peso",
            "de" to "Mexikanischer Peso",
            "el" to "Πέσο Μεξικού",
            "en" to "Mexican Peso",
            "es" to "Peso mexicano",
            "et" to "Mehhiko peeso",
            "fi" to "Meksikon peso",
            "fr" to "Peso mexicain",
            "hi" to "मेक्सिकन पेसो",
            "hu" to "Mexikói peso",
            "id" to "Peso Meksiko",
            "it" to "Peso messicano",
            "ja" to "メキシコ・ペソ",
            "ko" to "멕시코 페소",
            "lt" to "Meksikos pesas",
            "lv" to "Meksikas peso",
            "nl" to "Mexikaanse peso",
            "no" to "Mexikansk peso",
            "pl" to "Peso meksykańskie",
            "pt-BR" to "Peso mexicano",
            "ro" to "Peso mexican",
            "ru" to "Мексиканское песо",
            "sk" to "Mexické peso",
            "sl" to "Mehiški peso",
            "sr" to "Мексички песо",
            "sv" to "Mexikansk peso",
            "tr" to "Meksika Pesosu",
            "uk" to "Мексиканське песо",
            "zh" to "墨西哥比索"
        ),
        "NOK" to mapOf(
            "ar" to "كرونة نرويجية",
            "bg" to "Норвежка крона",
            "cs" to "Norská koruna",
            "da" to "Norsk krone",
            "de" to "Norwegische Krone",
            "el" to "Κορόνα Νορβηγίας",
            "en" to "Norwegian Krone",
            "es" to "Corona noruega",
            "et" to "Norra kroon",
            "fi" to "Norjan kruunu",
            "fr" to "Couronne norvégienne",
            "hi" to "नार्वेजियन क्रोन",
            "hu" to "Norvég korona",
            "id" to "Krone Norwegia",
            "it" to "Corona norvegese",
            "ja" to "ノルウェー・クローネ",
            "ko" to "노르웨이 크로네",
            "lt" to "Norvegijos krona",
            "lv" to "Norvēģijas krona",
            "nl" to "Noorse kroon",
            "no" to "Norsk krone",
            "pl" to "Korona norweska",
            "pt-BR" to "Coroa norueguesa",
            "ro" to "Coroană norvegiană",
            "ru" to "Норвежская крона",
            "sk" to "Nórska koruna",
            "sl" to "Norveška krona",
            "sr" to "Норвешка круна",
            "sv" to "Norsk krona",
            "tr" to "Norveç Kronu",
            "uk" to "Норвезька крона",
            "zh" to "挪威克朗"
        ),
        "NZD" to mapOf(
            "ar" to "دولار نيوزيلندي",
            "bg" to "Новозеландски долар",
            "cs" to "Novozélandský dolar",
            "da" to "Newzealandsk dollar",
            "de" to "Neuseeland-Dollar",
            "el" to "Δολάριο Νέας Ζηλανδίας",
            "en" to "New Zealand Dollar",
            "es" to "Dólar neozelandés",
            "et" to "Uus-Meremaa dollar",
            "fi" to "Uuden-Seelannin dollari",
            "fr" to "Dollar néo-zélandais",
            "hi" to "न्यूजीलैंड डॉलर",
            "hu" to "Új-zélandi dollár",
            "id" to "Dolar Selandia Baru",
            "it" to "Dollaro neozelandese",
            "ja" to "ニュージーランド・ドル",
            "ko" to "뉴질랜드 달러",
            "lt" to "Naujosios Zelandijos doleris",
            "lv" to "Naujaisēlandes dolārs",
            "nl" to "Nieuw-Zeelandse dollar",
            "no" to "Newzealandsk dollar",
            "pl" to "Dolar nowozelandzki",
            "pt-BR" to "Dólar neozelandês",
            "ro" to "Dollar neozeelandez",
            "ru" to "Новозеландский доллар",
            "sk" to "Novozélandský dolár",
            "sl" to "Novozelandski dolar",
            "sr" to "Новозеландски долар",
            "sv" to "Nyzealandsk dollar",
            "tr" to "Yeni Zelanda Doları",
            "uk" to "Новозеландський долар",
            "zh" to "新西兰元"
        ),
        "RON" to mapOf(
            "ar" to "ليو روماني",
            "bg" to "Румънска лея",
            "cs" to "Rumunský leu",
            "da" to "Rumænsk leu",
            "de" to "Rumänischer Leu",
            "el" to "Λέου Ρουμανίας",
            "en" to "Romanian Leu",
            "es" to "Leu rumano",
            "et" to "Rumeenia leu",
            "fi" to "Romanian leu",
            "fr" to "Leu roumain",
            "hi" to "रोमानियन लेउ",
            "hu" to "Román lej",
            "id" to "Leu Rumania",
            "it" to "Leu rumeno",
            "ja" to "ルーマニア・レウ",
            "ko" to "루마니아 레우",
            "lt" to "Rumunijos lėja",
            "lv" to "Rumānijas leja",
            "nl" to "Roemeense leu",
            "no" to "Rumensk leu",
            "pl" to "Lej rumuński",
            "pt-BR" to "Leu romeno",
            "ro" to "Leu românesc",
            "ru" to "Румынский лей",
            "sk" to "Rumunské leu",
            "sl" to "Romunski lev",
            "sr" to "Румунски леј",
            "sv" to "Rumänsk leu",
            "tr" to "Rumen Leyi",
            "uk" to "Румунський лей",
            "zh" to "罗马尼亚列伊"
        ),
        "SEK" to mapOf(
            "ar" to "كرونة السويدية",
            "bg" to "Шведска крона",
            "cs" to "Švédská koruna",
            "da" to "Svensk krone",
            "de" to "Schwedische Krone",
            "el" to "Κορόνα Σουηδίας",
            "en" to "Swedish Krona",
            "es" to "Corona sueca",
            "et" to "Rootsi kroon",
            "fi" to "Ruotsin kruunu",
            "fr" to "Couronne suédoise",
            "hi" to "स्वीडिश क्रोना",
            "hu" to "Svéd korona",
            "id" to "Krona Swedia",
            "it" to "Corona svedese",
            "ja" to "スウェーデン・クローナ",
            "ko" to "스웨덴 크로네",
            "lt" to "Švedijos krona",
            "lv" to "Zviedrijas krona",
            "nl" to "Zweedse kroon",
            "no" to "Svensk krone",
            "pl" to "Korona szwedzka",
            "pt-BR" to "Coroa sueca",
            "ro" to "Coroană suedeză",
            "ru" to "Шведская крона",
            "sk" to "Švédska koruna",
            "sl" to "Švedska krona",
            "sr" to "Шведска круна",
            "sv" to "Svensk krona",
            "tr" to "İsveç Kronu",
            "uk" to "Шведська крона",
            "zh" to "瑞典克朗"
        ),
        "SGD" to mapOf(
            "ar" to "دولار سنغافوري",
            "bg" to "Сингапурски долар",
            "cs" to "Singapurský dolar",
            "da" to "Singaporeansk dollar",
            "de" to "Singapur-Dollar",
            "el" to "Δολάριο Σινγκαπούρης",
            "en" to "Singapore Dollar",
            "es" to "Dólar singapurense",
            "et" to "Singapuri dollar",
            "fi" to "Singaporen dollari",
            "fr" to "Dollar de Singapour",
            "hi" to "सिंगापुर डॉलर",
            "hu" to "Szingapúri dollár",
            "id" to "Dolar Singapura",
            "it" to "Dollaro di Singapour",
            "ja" to "シンガポール・ドル",
            "ko" to "싱가포르 달러",
            "lt" to "Singapūro doleris",
            "lv" to "Singapūras dolārs",
            "nl" to "Singaporese dollar",
            "no" to "Singaporsk dollar",
            "pl" to "Dolar singapurski",
            "pt-BR" to "Dólar de Cingapura",
            "ro" to "Dollar singaporez",
            "ru" to "Сингапурский доллар",
            "sk" to "Singapurský dolár",
            "sl" to "Singapurski dolar",
            "sr" to "Сингапурски долар",
            "sv" to "Singaporiansk dollar",
            "tr" to "Singapur Doları",
            "uk" to "Сінгапурський долар",
            "zh" to "新加坡元"
        ),
        "THB" to mapOf(
            "ar" to "บาท تايلاندي",
            "bg" to "Тайландски бат",
            "cs" to "Thajský baht",
            "da" to "Thailandsk baht",
            "de" to "Thailändischer Baht",
            "el" to "Μπατ Ταϊλάνδης",
            "en" to "Thai Baht",
            "es" to "Baht tailandés",
            "et" to "Tai baat",
            "fi" to "Thaimaan baht",
            "fr" to "Baht thaïlandais",
            "hi" to "थाई बहत",
            "hu" to "Thaiföldi baht",
            "id" to "Baht Thailand",
            "it" to "Baht thailandese",
            "ja" to "タイ・バーツ",
            "ko" to "태국 바트",
            "lt" to "Tailando batas",
            "lv" to "Taizemes bāts",
            "nl" to "Thaise baht",
            "no" to "Thailandsk baht",
            "pl" to "Baht tajski",
            "pt-BR" to "Baht tailandês",
            "ro" to "Baht thailandez",
            "ru" to "Тайский бат",
            "sk" to "Thajský baht",
            "sl" to "Tajski baht",
            "sr" to "Тајландски бат",
            "sv" to "Thailandsk baht",
            "tr" to "Tayland Bahtı",
            "uk" to "Тайський бат",
            "zh" to "泰铢"
        ),
        "VND" to mapOf(
            "ar" to "دونغ فيتنامي",
            "bg" to "Виетнамски донг",
            "cs" to "Vietnamský dong",
            "da" to "Vietnamesisk dong",
            "de" to "Vietnamesischer Đồng",
            "el" to "Ντονγκ Βιετνάμ",
            "en" to "Vietnamese Đồng",
            "es" to "Dong vietnamita",
            "et" to "Vietnami dong",
            "fi" to "Vietnamin dong",
            "fr" to "Đồng vietnamien",
            "hi" to "वियतनामी डोंग",
            "hu" to "Vietnámi dong",
            "id" to "Dong Vietnam",
            "it" to "Dong vietnamita",
            "ja" to "ベトナム・ドン",
            "ko" to "베트ナム 동",
            "lt" to "Vietnamo dongas",
            "lv" to "Vjetnamas dongs",
            "nl" to "Vietnamese dong",
            "no" to "Vietnamesisk dong",
            "pl" to "Dong wietnamski",
            "pt-BR" to "Dong vietnamita",
            "ro" to "Dong vietnamez",
            "ru" to "Вьетнамский донг",
            "sk" to "Vietnamský dong",
            "sl" to "Vietnamski dong",
            "sr" to "Вијетнамски донг",
            "sv" to "Vietnamesisk dong",
            "tr" to "Vietnam Dongu",
            "uk" to "В'єтнамський донг",
            "zh" to "越南盾"
        ),
        "ZAR" to mapOf(
            "ar" to "راند جنوب أفريقيا",
            "bg" to "Южноафрикански ранд",
            "cs" to "Jihoafrický rand",
            "da" to "Sydafrikansk rand",
            "de" to "Südafrikanischer Rand",
            "el" to "Ραντ Νότιας Αφρικής",
            "en" to "South African Rand",
            "es" to "Rand sudafricano",
            "et" to "Lõuna-Aafrika rand",
            "fi" to "Etelä-Afrikan randi",
            "fr" to "Rand sud-africain",
            "hi" to "दक्षिण अफ्रीकी रैंड",
            "hu" to "Dél-afrikai rand",
            "id" to "Rand Afrika Selatan",
            "it" to "Rand sudafricano",
            "ja" to "南アフリカ・ランド",
            "ko" to "남アフ리카 랜드",
            "lt" to "PAR randas",
            "lv" to "Dienvidāfrikas rands",
            "nl" to "Zuid-Afrikaanse rand",
            "no" to "Sørafrikansk rand",
            "pl" to "Rand południowoafrykański",
            "pt-BR" to "Rand sul-africano",
            "ro" to "Rand sud-african",
            "ru" to "Южноафриканский рэнд",
            "sk" to "Juhoafrický rand",
            "sl" to "Južnoafriški rand",
            "sr" to "Јужноафрички ранд",
            "sv" to "Sydafrikansk rand",
            "tr" to "Güney Afrika Randı",
            "uk" to "Південноафриканський ранд",
            "zh" to "南非兰特"
        )
    )

    fun getName(code: String, language: String): String {
        val normalizedCode = code.uppercase()
        val normalizedLanguage = normalizeLanguage(language)

        val map = names[normalizedCode]
        return map?.get(normalizedLanguage)
            ?: map?.get("en")
            ?: CurrencyCatalog.getByCode(normalizedCode)?.code
            ?: normalizedCode
    }

    fun getDisplayLabel(code: String, language: String): String {
        val info = CurrencyCatalog.getByCode(code)
            ?: return code.uppercase()

        val name = getName(info.code, language)
        return "${info.code} (${info.symbol}) — $name"
    }

    private fun normalizeLanguage(lang: String): String {
        val value = lang.trim()
        return when {
            value.contains("-") -> value.substringBefore("-").lowercase()
            value.contains("_") -> value.substringBefore("_").lowercase()
            else -> value.lowercase()
        }
    }
}