name: CI (Android + Real iOS Device)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Android debug
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/debug/*.apk

  ios-device:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build iOS Device Framework (KMP)
        # ИСПРАВЛЕНО: Теперь собираем под реальное железо (IosArm64)
        run: ./gradlew :composeApp:linkDebugFrameworkIosArm64

      - name: Upload iOS framework (Real Device)
        uses: actions/upload-artifact@v4
        with:
          name: ios-real-device-framework
          # ИСПРАВЛЕНО: Путь к файлам для реального устройства
          path: composeApp/build/bin/iosArm64/debugFramework/
