name: CI (Android + Real iOS Device)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Android debug
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/debug/*.apk

  ios-device:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build iOS App Binary (Real Device)
        # Собираем полноценный исполняемый файл вместо фреймворка
        run: ./gradlew :composeApp:iosArm64Binaries

      - name: Upload iOS App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          # Путь к исполняемому файлу и ресурсам
          path: composeApp/build/bin/iosArm64/debugExe/
